---
apiVersion: v1
kind: Service
metadata:
  name: google-cloud-mockserver
spec:
  selector:
    app: google-cloud-mockserver
  ports:
  - protocol: TCP
    port: 80
    name: mockserver-port
    targetPort: 1080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: google-cloud-mockserver
  labels:
    app: google-cloud-mockserver
spec:
  minReadySeconds: 5
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: google-cloud-mockserver
    spec:
      containers:
      - name: google-cloud-mockserver
        image: gcr.io/seventh-chassis-87509/mockserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 1080
            httpHeaders:
            - name: X-Custom-Header
              value: Test
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 1080
            httpHeaders:
            - name: X-Custom-Header
              value: Test
          initialDelaySeconds: 30
          periodSeconds: 30
